---
title: "My English Activity Log : MEAL"
author:
  - name: "Decoux Benjamin" 
date: "`r Sys.Date()`"
categories:
  - "English for Science"
  - "M.E.A.L."
output: distill::distill_article
---


Hey, you will see here my daily English activities (I'm starting it a bit late because of a problem that i had with my blog) !

One of my favorite activity in English is to translate songs so you will notice that there will be a lot of "today i watched the lyrics of X songs"


- At the start of December i changed my language (on my computer) from French to English and that applies to games, desk , programs, research, ...

- As i am very interested in video games I'm trying to watch more and more videos and streams in English (championships, tutorial,...)
-
7/02/2021 => tried to understand the lyrics of "Wellerman" from The longest jhons that went viral on the net but it was pretty hard to understand.
I also watched the lyrics of "we will rock you" form queen it was way more easier . The best things i learned is that " to rock" mean "secouer" in French!

