---
title: "pain relief for irritable bowel syndrome"
description: |
  Second analysis about venom in medicine.
author:
  - name: Decoux Benjamin
    url: {}
date: 02-07-2021
categories:
  - "English for Science"
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Article information

Source: https://www.sciencedaily.com/releases/2020/09/200921100347.htm

Word count: 521

Date of publication: September 21, 2020 

## Vocabulary

| Word from the text | Synonym/definition in English | French Translate         |
| ------------------ | ----------------------------- | ------------------------ |
| Bowel              | Gut                           | Intestin                 |
| Span               | Stretch                       | Envergure                |
| Pain relief        | painkiller/analgesic          | Anti-douleur/analgésique |
| To screen          | To examine/review             | Examiner                 |
| Array              | Arrangement                   | Arsenal/gamme/éventail   |
| Potent             | efficient                     | Efficace                 |
| Bladder            |   /                           | Vessie                   |

## Analysis table

| Basic article information 	| / 	|
|------------------------------	|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|
| Researchers 	| University of Queensland-led researchers .           	|
| General topic? 	| Reschearchers wants to use the venom of the Venezuelan Pinkfoot Goliath tarantula to create a pain relief for irritable bowel syndrome (IBS). IBS is a common condition that affects the digestive system that can last for days, month, or even for life.	|
| Procedure/what was examined? 	| Pains in these diseases are mainly due to hypersensitivity of nerves with a wide array of voltage-gated ion channels.So they were looking for specific peptides in the venom that could be potent and at the same time target sodium channels related to the visceral pain (and only this one) and inhibit them . 	|
| Conclusions/discovery? 	| They found 2 of these rare peptides with one particularly potent at reducing the  sensory nerves of the bladder and close to stop the chronic pain in the IBS. The more efficient one is now a potential treatment for pain in IBS|
| The bonus of research! 	| More than that the understanding of the structure and functions of peptides in these spider venoms has made a huge progress.The others peptides can maybe be used as tools to understand drivers of pain in different diseases.
